zookeeper:
  image: rridgley1/zk-exhibitor:3.4.7
  container_name: zookeeper
  hostname: zookeeper
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    - "8181:8181"
kafka:
  build: .
  expose:
    - "9092"
    - "9999"
  ports:
    - "9092:9092"
    - "9999:9999"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
    KAFKA_ADVERTISED_PORT: "9092"
    KAFKA_DEFAULT_TOPIC: "events"
    JMX_PORT: "9999"
    KAFKA_ZOOKEEPER_CONNECT: zk:2181
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
    KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "60000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafkamanager:
  image: sheepkiller/kafka-manager:1.2.9.10
  expose:
    - 9000
  ports:
    - 9000:9000
  links:
    - zookeeper:zk
    - kafka:kafka
  environment:
    ZK_HOSTS: zk:2181
    APPLICATION_SECRET: "letmein"